[Phi,Lam,Midx,diagKs]=Get_Modal_v2;
len1=1:1:3636;
w1=~ismember(len1,diagKs);
finalmodaldispl=[];
finalmodalforce=[];
ff1=linspace(-1,1,10);
sf=1e-1:1e-1:1e+0;
for k=1:length(sf)
    allmodaldispl=[];
    allmodalforce=[];
    for i=1:length(ff1)
        filename = strcat('force','_',num2str(k),'_',num2str(i),'.csv');
        disp1 = csvread(filename,1,0);
        disp1=disp1.';
        disp1=disp1(:);
        disp1=disp1(w1);
        modaldispl=real(Phi\disp1);
        modalforce=zeros(length(modaldispl),1);
        modalforce(1)=(ff1(i))*sf(k);
        allmodaldispl=horzcat(allmodaldispl,modaldispl);
        allmodalforce=horzcat(allmodalforce,modalforce);
    end
    finalmodaldispl(:,:,k)=allmodaldispl;
    finalmodalforce(:,:,k)=allmodalforce;
end
thetaf3=[];
thetaf9=[];
for k=1:length(sf)
    q1=finalmodaldispl(1,:,k);
    fq1=finalmodalforce(1,:,k);
    fq2=fq1.';%-Lam(1)*q1.';
    q1=q1.';
    A=[q1];
    w=rms(A);
    Aw=bsxfun(@rdivide,A,w);
    bw=Aw\fq2;
    theta11=bw./w';
    thetaf9=horzcat(thetaf9,theta11);
    A=[q1.^2 q1.^3];
    w=rms(A);
    Aw=bsxfun(@rdivide,A,w);
    bw=Aw\fq2;
    theta11=bw./w';
    thetaf3=horzcat(thetaf3,theta11);
end